# -*- coding: utf-8 -*-
"""CLASE 4 - GENERACIÓN DE GRAFICOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16X9DSswN_Jgjtf92uEjZawzbcq4aCc3E
"""

# ==============================================================================
# DASHBOARD EJECUTIVO COMERCIAL 2024 CON FILTRO NATIVO DINÁMICO (PLOTLY)
# ==============================================================================

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ------------------------------------------------------------------------------
# 1. CARGA DEL DATASET
# ------------------------------------------------------------------------------
archivo_excel = 'Dataset_Visualizacion_Reporte_Empresarial_Sesion4.xlsx'
df = pd.read_excel(archivo_excel, sheet_name='Data_Ventas_Historica')

print(f"✓ Dataset cargado exitosamente: {len(df)} registros.")

# Paleta corporativa
COLOR_NAVY = '#1E1B4B'
COLOR_BLUE = '#2563EB'
COLOR_RED = '#DC2626'
COLOR_GREEN = '#10B981'
COLOR_MUTED = '#CBD5E1'
COLOR_CANAL = ['#1E1B4B', '#3B82F6', '#10B981', '#F59E0B']

# Listas maestras para mantener consistencia en los ejes
meses_orden = list(df['Mes_Nombre'].unique())
categorias_orden = list(df.groupby('Categoria')['Venta_Real_USD'].sum().sort_values().index)
canales_orden = list(df['Canal_Venta'].unique())
regiones_orden = list(df.groupby('Region')['Ganancia_USD'].sum().sort_values(ascending=False).index)

# Opciones de filtro: Consolidado global + cada región
opciones_filtro = ['Todas las Regiones'] + regiones_orden

# ------------------------------------------------------------------------------
# 2. CONFIGURACIÓN DEL LIENZO 2x2
# ------------------------------------------------------------------------------
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        "<b>A. Evolución Mensual vs Meta Comercial</b>",
        "<b>B. Ranking de Ventas por Categoría</b>",
        "<b>C. Mix de Ingresos por Canal</b>",
        "<b>D. Ganancia Neta por Región</b>"
    ),
    specs=[
        [{"type": "xy"}, {"type": "xy"}],
        [{"type": "domain"}, {"type": "xy"}]
    ],
    vertical_spacing=0.16,
    horizontal_spacing=0.10
)

# ------------------------------------------------------------------------------
# 3. GENERACIÓN DE TRAZAS PRECALCULADAS POR CADA OPCIÓN DE FILTRO
# ------------------------------------------------------------------------------
# Cada opción del filtro genera 5 trazas (2 en Q1, 1 en Q2, 1 en Q3, 1 en Q4)
for idx_opcion, region_sel in enumerate(opciones_filtro):
    # La primera opción ("Todas las Regiones") se muestra activa por defecto
    activo_inicial = (idx_opcion == 0)

    if region_sel == 'Todas las Regiones':
        df_sub = df
        colores_barras_reg = [COLOR_GREEN] * len(regiones_orden)
    else:
        df_sub = df[df['Region'] == region_sel]
        # Resalta la región seleccionada y atenúa las demás en gris
        colores_barras_reg = [COLOR_GREEN if r == region_sel else COLOR_MUTED for r in regiones_orden]

    # Agrupaciones con reindexación para evitar desalineación de ejes
    df_mes_sub = (
        df_sub.groupby('Mes_Nombre', sort=False)[['Venta_Real_USD', 'Meta_Ventas_USD']]
        .sum()
        .reindex(meses_orden, fill_value=0)
    )
    df_cat_sub = (
        df_sub.groupby('Categoria')['Venta_Real_USD']
        .sum()
        .reindex(categorias_orden, fill_value=0)
    )
    df_canal_sub = (
        df_sub.groupby('Canal_Venta')['Venta_Real_USD']
        .sum()
        .reindex(canales_orden, fill_value=0)
    )
    df_reg_total = (
        df.groupby('Region')['Ganancia_USD']
        .sum()
        .reindex(regiones_orden, fill_value=0)
    )

    # --- CUADRANTE 1: Venta Real vs Meta ---
    fig.add_trace(
        go.Scatter(
            x=df_mes_sub.index,
            y=df_mes_sub['Venta_Real_USD'],
            name='Venta Real',
            mode='lines+markers',
            line=dict(color=COLOR_BLUE, width=3),
            fill='tozeroy',
            fillcolor='rgba(37, 99, 235, 0.12)',
            hovertemplate='<b>Mes:</b> %{x}<br><b>Venta Real:</b> $%{y:,.0f}<extra></extra>',
            visible=activo_inicial,
            legendgroup='Venta Real',
            showlegend=activo_inicial
        ),
        row=1, col=1
    )

    fig.add_trace(
        go.Scatter(
            x=df_mes_sub.index,
            y=df_mes_sub['Meta_Ventas_USD'],
            name='Meta Comercial',
            mode='lines',
            line=dict(color=COLOR_RED, width=3, dash='dash'),
            hovertemplate='<b>Mes:</b> %{x}<br><b>Meta:</b> $%{y:,.0f}<extra></extra>',
            visible=activo_inicial,
            legendgroup='Meta Comercial',
            showlegend=activo_inicial
        ),
        row=1, col=1
    )

    # --- CUADRANTE 2: Barras por Categoría ---
    fig.add_trace(
        go.Bar(
            y=df_cat_sub.index,
            x=df_cat_sub.values,
            orientation='h',
            name='Venta Categoría',
            marker=dict(color=COLOR_NAVY),
            text=[f"${v:,.0f}" if v > 0 else "$0" for v in df_cat_sub.values],
            textposition='outside',
            hovertemplate='<b>Categoría:</b> %{y}<br><b>Venta:</b> $%{x:,.0f}<extra></extra>',
            visible=activo_inicial,
            showlegend=False
        ),
        row=1, col=2
    )

    # --- CUADRANTE 3: Donut por Canal ---
    fig.add_trace(
        go.Pie(
            labels=df_canal_sub.index,
            values=df_canal_sub.values,
            hole=0.5,
            name='Canal',
            marker=dict(colors=COLOR_CANAL, line=dict(color='#FFFFFF', width=2)),
            textinfo='label+percent',
            hovertemplate='<b>Canal:</b> %{label}<br><b>Venta:</b> $%{value:,.0f}<br><b>Share:</b> %{percent}<extra></extra>',
            visible=activo_inicial,
            showlegend=False
        ),
        row=2, col=1
    )

    # --- CUADRANTE 4: Ganancia por Región (Con resalte dinámico) ---
    fig.add_trace(
        go.Bar(
            x=df_reg_total.index,
            y=df_reg_total.values,
            name='Ganancia Región',
            marker=dict(color=colores_barras_reg),
            text=[f"${v:,.0f}" for v in df_reg_total.values],
            textposition='outside',
            hovertemplate='<b>Región:</b> %{x}<br><b>Ganancia:</b> $%{y:,.0f}<extra></extra>',
            visible=activo_inicial,
            showlegend=False
        ),
        row=2, col=2
    )

# ------------------------------------------------------------------------------
# 4. CONSTRUCCIÓN DEL MENÚ DESPLEGABLE (UPDATEMENUS)
# ------------------------------------------------------------------------------
total_trazas = len(opciones_filtro) * 5
botones = []

for i, opcion in enumerate(opciones_filtro):
    # Genera máscara booleana que activa únicamente las 5 trazas de la opción elegida
    mascara_visibilidad = [False] * total_trazas
    for t in range(5):
        mascara_visibilidad[i * 5 + t] = True

    etiqueta = "🌐 Todas las Regiones" if opcion == 'Todas las Regiones' else f"📍 Región: {opcion}"
    titulo_dinamico = (
        "<b>CUADRO DE MANDO EJECUTIVO DE RENDIMIENTO COMERCIAL 2024</b>"
        if opcion == 'Todas las Regiones'
        else f"<b>CUADRO DE MANDO EJECUTIVO 2024 — {opcion.upper()}</b>"
    )

    botones.append(
        dict(
            label=etiqueta,
            method="update",
            args=[
                {"visible": mascara_visibilidad},
                {"title.text": titulo_dinamico}
            ]
        )
    )

# ------------------------------------------------------------------------------
# 5. AJUSTES DE FORMATO Y ESTILO GLOBAL
# ------------------------------------------------------------------------------
fig.update_layout(
    title=dict(
        text="<b>CUADRO DE MANDO EJECUTIVO DE RENDIMIENTO COMERCIAL 2024</b>",
        font=dict(size=17, color=COLOR_NAVY, family="sans-serif"),
        x=0.5,
        xanchor='center',
        y=0.98
    ),
    template='plotly_white',
    height=860,
    hoverlabel=dict(bgcolor="white", font_size=12, font_family="sans-serif"),
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.03,
        xanchor="right",
        x=1.0
    ),
    margin=dict(t=130, b=50, l=60, r=60),
    updatemenus=[
        dict(
            buttons=botones,
            direction="down",
            pad={"r": 8, "t": 4},
            showactive=True,
            x=0.15,
            xanchor="left",
            y=1.12,
            yanchor="middle",
            bgcolor="#FFFFFF",
            bordercolor="#CBD5E1",
            font=dict(size=11, color=COLOR_NAVY)
        )
    ],
    annotations=[
        dict(
            text="<b>Filtrar por Región:</b>",
            x=0.0,
            y=1.12,
            xref="paper",
            yref="paper",
            showarrow=False,
            font=dict(size=12, color=COLOR_NAVY),
            xanchor="left",
            yanchor="middle"
        )
    ]
)

# Formateo monetario en los ejes numéricos
fig.update_yaxes(tickprefix="$", tickformat=",.0f", row=1, col=1)
fig.update_xaxes(tickprefix="$", tickformat=",.0f", row=1, col=2)
fig.update_yaxes(tickprefix="$", tickformat=",.0f", row=2, col=2)

# ------------------------------------------------------------------------------
# 6. EXPORTAR Y MOSTRAR
# ------------------------------------------------------------------------------
fig.write_html('Dashboard_Ejecutivo_Interactivo.html')
print("✓ Reporte interactivo con filtros guardado como 'Dashboard_Ejecutivo_Interactivo.html'.")

fig.show()



# ------------------------------------------------------------------------------
# 3. GRÁFICO DE LÍNEAS TEMPORALES: VENTAS REALES VS METAS COMERCIALES
# ------------------------------------------------------------------------------
df_mes = df.groupby('Mes_Nombre', sort=False)[['Venta_Real_USD', 'Meta_Ventas_USD']].sum()

fig, ax = plt.subplots(figsize=(10, 4.8))

# Línea de Venta Real con área sombreada
ax.plot(df_mes.index, df_mes['Venta_Real_USD'], marker='o', linewidth=2.5,
        color='#2563EB', label='Venta Real Facturada')
ax.fill_between(df_mes.index, df_mes['Venta_Real_USD'], alpha=0.12, color='#2563EB')

# Línea de Meta punteada
ax.plot(df_mes.index, df_mes['Meta_Ventas_USD'], linestyle='--', linewidth=6,
        color='#DC2626', label='Meta Comercial')

ax.set_title('Evolución Mensual de Ventas vs Meta de Negocio 2024', fontsize=13, fontweight='bold', pad=12)
ax.tick_params(axis='x', rotation=40)
ax.yaxis.set_major_formatter('${x:,.0f}')
ax.spines[['top', 'right']].set_visible(False)
ax.grid(True, linestyle=':', alpha=0.5)
ax.legend(frameon=True, loc='upper left')
plt.tight_layout()
plt.show()

# ------------------------------------------------------------------------------
# 4. GRÁFICO DE DONUT: PARTICIPACIÓN DE INGRESOS POR CANAL COMERCIAL
# ------------------------------------------------------------------------------
df_canal = df.groupby('Canal_Venta')['Venta_Real_USD'].sum()

fig, ax = plt.subplots(figsize=(7, 4.5))
colores = ['#1E1B4B', '#3B82F6', '#10B981']

wedges, texts, autotexts = ax.pie(
    df_canal,
    labels=df_canal.index,
    autopct='%1.1f%%',
    startangle=180,
    colors=colores,
    wedgeprops={'width': 0.45, 'edgecolor': 'BLACK', 'linewidth': 1},
    pctdistance=0.75
)

# Estilización de los porcentajes dentro del donut
for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontweight('bold')
    autotext.set_fontsize(20)

ax.set_title('Mix de Ingresos por Canal Comercial', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# ------------------------------------------------------------------------------
# 5. DASHBOARD EJECUTIVO CONSOLIDADO 2x2 (ALTA RESOLUCIÓN)
# ------------------------------------------------------------------------------
fig, axs = plt.subplots(2, 2, figsize=(15, 9.5))
fig.suptitle('CUADRO DE MANDO EJECUTIVO DE RENDIMIENTO COMERCIAL 2024',
             fontsize=15, fontweight='bold', color='#1E1B4B', y=0.98)

# Cuadrante 1: Línea Temporal
axs[0, 0].plot(df_mes.index, df_mes['Venta_Real_USD'], marker='o', color='#2563EB', linewidth=2)
axs[0, 0].plot(df_mes.index, df_mes['Meta_Ventas_USD'], linestyle='--', color='#DC2626', linewidth=1.5)
axs[0, 0].set_title('A. Evolución Mensual vs Meta', fontweight='bold', fontsize=11)
axs[0, 0].tick_params(axis='x', rotation=45, labelsize=9)
axs[0, 0].grid(True, linestyle=':', alpha=0.4)

# Cuadrante 2: Barras por Categoría
bars2 = axs[0, 1].barh(df_cat.index, df_cat.values, color='#1E1B4B', height=0.55)
axs[0, 1].set_title('B. Ventas Totales por Categoría', fontweight='bold', fontsize=11)
axs[0, 1].spines[['top', 'right']].set_visible(False)

# Cuadrante 3: Donut por Canal
axs[1, 0].pie(df_canal, labels=df_canal.index, autopct='%1.0f%%', colors=colores,
              wedgeprops={'width': 0.45, 'edgecolor': 'white', 'linewidth': 1.5})
axs[1, 0].set_title('C. Participación por Canal de Venta', fontweight='bold', fontsize=11)

# Cuadrante 4: Ganancia Neta por Región
df_reg = df.groupby('Region')['Ganancia_USD'].sum().sort_values(ascending=False)
axs[1, 1].bar(df_reg.index, df_reg.values, color='#10B981', width=0.55)
axs[1, 1].set_title('D. Ganancia Neta por Región Geográfica', fontweight='bold', fontsize=11)
axs[1, 1].spines[['top', 'right']].set_visible(False)
axs[1, 1].yaxis.set_major_formatter('${x:,.0f}')

plt.tight_layout(pad=2.8)

# Guardar en alta calidad (300 DPI) para reportes y presentaciones
plt.savefig('Dashboard_Ejecutivo_Sesion4.png', dpi=300, bbox_inches='tight')
print("✓ Reporte visual exportado exitosamente como 'Dashboard_Ejecutivo_Sesion4.png' (300 DPI).")
plt.show()